use std::fmt;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A value failed the syntax rules for an identifier.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("invalid {kind}: {reason}")]
pub struct InvalidId {
    pub kind: &'static str,
    pub reason: &'static str,
}

/// Correlation key chosen by the worker. Unique within a session; the Core
/// rejects a repeated value instead of executing the request again.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct RequestId(String);

impl RequestId {
    pub const MAX_LEN: usize = 64;

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for RequestId {
    type Error = InvalidId;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        let invalid = |reason| InvalidId {
            kind: "request_id",
            reason,
        };
        if value.is_empty() {
            return Err(invalid("must not be empty"));
        }
        if value.len() > Self::MAX_LEN {
            return Err(invalid("must be at most 64 characters"));
        }
        if !value
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
        {
            return Err(invalid(
                "may contain only ASCII letters, digits, '-' and '_'",
            ));
        }
        Ok(Self(value))
    }
}

impl From<RequestId> for String {
    fn from(value: RequestId) -> Self {
        value.0
    }
}

impl fmt::Display for RequestId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

macro_rules! core_id {
    ($(#[$doc:meta])* $name:ident, $kind:literal) => {
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
        #[serde(try_from = "String", into = "String")]
        pub struct $name(Uuid);

        impl $name {
            /// Time-ordered (UUIDv7), so IDs sort by creation time.
            pub fn new() -> Self {
                Self(Uuid::now_v7())
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl TryFrom<String> for $name {
            type Error = InvalidId;

            /// Only the hyphenated form, which is the only form the Core
            /// emits; the braced, simple and URN spellings are refused.
            fn try_from(value: String) -> Result<Self, Self::Error> {
                let invalid = InvalidId {
                    kind: $kind,
                    reason: "must be a hyphenated UUID",
                };
                if value.len() != 36 {
                    return Err(invalid);
                }
                Uuid::parse_str(&value).map(Self).map_err(|_| invalid)
            }
        }

        impl std::str::FromStr for $name {
            type Err = InvalidId;

            fn from_str(value: &str) -> Result<Self, Self::Err> {
                Self::try_from(value.to_owned())
            }
        }

        impl From<$name> for String {
            fn from(value: $name) -> Self {
                value.0.hyphenated().to_string()
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                fmt::Display::fmt(&self.0.hyphenated(), f)
            }
        }
    };
}

core_id!(
    /// Identifies one worker session. Generated by the Core at handshake.
    SessionId,
    "session_id"
);
core_id!(
    /// Identifies one durable task. Generated by the Core, never by a worker.
    TaskId,
    "task_id"
);

/// Name of a tool, such as `system.info`. Syntax only: whether the tool
/// exists is decided by [`crate::ToolCall::from_request`], so that an unknown
/// but well-formed name can be recorded and rejected as `unknown_tool`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct ToolName(String);

impl ToolName {
    pub const MAX_LEN: usize = 64;

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ToolName {
    type Error = InvalidId;

    /// Two or more dot-separated segments; each starts with a lowercase
    /// letter and continues with lowercase letters, digits or `_`.
    fn try_from(value: String) -> Result<Self, Self::Error> {
        let invalid = |reason| InvalidId {
            kind: "tool",
            reason,
        };
        if value.len() > Self::MAX_LEN {
            return Err(invalid("must be at most 64 characters"));
        }
        let mut segments = 0;
        for segment in value.split('.') {
            let mut bytes = segment.bytes();
            match bytes.next() {
                Some(b) if b.is_ascii_lowercase() => {}
                _ => return Err(invalid("each segment must start with a lowercase letter")),
            }
            if !bytes.all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_') {
                return Err(invalid(
                    "segments may contain only lowercase letters, digits and '_'",
                ));
            }
            segments += 1;
        }
        if segments < 2 {
            return Err(invalid("must have at least two dot-separated segments"));
        }
        Ok(Self(value))
    }
}

impl From<ToolName> for String {
    fn from(value: ToolName) -> Self {
        value.0
    }
}

impl fmt::Display for ToolName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_id_accepts_simple_tokens() {
        for ok in ["r1", "req-001", "a_b-C", &"x".repeat(64)] {
            assert!(RequestId::try_from(ok.to_owned()).is_ok(), "{ok}");
        }
    }

    #[test]
    fn request_id_rejects_bad_tokens() {
        for bad in ["", "has space", "slash/", "ünicode", &"x".repeat(65)] {
            assert!(RequestId::try_from(bad.to_owned()).is_err(), "{bad}");
        }
    }

    #[test]
    fn tool_name_syntax() {
        for ok in ["system.info", "filesystem.read_fixture", "a.b.c2"] {
            assert!(ToolName::try_from(ok.to_owned()).is_ok(), "{ok}");
        }
        for bad in [
            "",
            "system",
            ".info",
            "system.",
            "System.info",
            "system..info",
            "system.1nfo",
            "system.info;rm",
            "shell exec",
        ] {
            assert!(ToolName::try_from(bad.to_owned()).is_err(), "{bad}");
        }
    }

    #[test]
    fn core_ids_round_trip_as_strings() {
        let id = TaskId::new();
        let text: String = id.into();
        assert_eq!(TaskId::try_from(text).unwrap(), id);
        assert!(TaskId::try_from("not-a-uuid".to_owned()).is_err());
        let simple = id.to_string().replace('-', "");
        assert!(TaskId::try_from(simple.clone()).is_err());
        assert!(TaskId::try_from(format!("{{{id}}}")).is_err());
        assert!(TaskId::try_from(format!("urn:uuid:{id}")).is_err());
    }
}
